-- Phase A2: dedicated service user for CI + autumneight automation.
-- Run as ACCOUNTADMIN (or SECURITYADMIN + SYSADMIN). Key-pair auth only — no password.
-- Private key stays on the runner (~/.snowflake/keys/svc_nhl_pipeline_key.p8 locally;
-- GitHub secret SNOWFLAKE_PRIVATE_KEY for CI; autumneight secret store for prod runs).

CREATE ROLE IF NOT EXISTS NHL_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE NHL_PIPELINE_ROLE;
GRANT USAGE ON DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT CREATE SCHEMA ON DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DBT_ANALYTICS TO ROLE NHL_PIPELINE_ROLE;

CREATE USER IF NOT EXISTS SVC_NHL_PIPELINE
    DEFAULT_ROLE = NHL_PIPELINE_ROLE
    DEFAULT_WAREHOUSE = DBT_WH
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0JAkyfrI3510eoAwUjmiT9MYJIjM1qVRE01SHEkwgpjL/1GYmtxzKk/9jLhCsA3crBmb9P/FWngIYEOIgsojJy3utCklkQ2Q3my/sJx0X4Y/t0evIcaowaEZb+bbslhm0TBd3b/EnkzLnXCL53F6g+5XFTUybi0ONU3Y/ZgBWZ0jaewrXVs+7Fx0mmcl9DOdZMva3C8ZH3zPlctBVrGNz/ZW5nxcgpEAd8qAVeOVNLxqDCJui/BCYaNlDh9A4RoLBDI6eUfnT0JTR7mhJbrsc4YbdakBQX8JijBksWcT5P0xpVnYaVVTIa/7r0O+SBG98zENbgzEmbri+lWro8brOwIDAQAB'
    COMMENT = 'Key-pair service user for NHL pipeline (CI + autumneight). No password.';

GRANT ROLE NHL_PIPELINE_ROLE TO USER SVC_NHL_PIPELINE;

-- Afterwards, rotate the human user's password (it has lived in .env):
-- ALTER USER <your_user> SET PASSWORD = '<new strong password>' MUST_CHANGE_PASSWORD = FALSE;
