version: 2

sources:
  - name: nhl_staging_data
    description: >
      Raw data loaded from the NHL API containing game data, player statistics, 
      team information, and standings. This source represents the foundation for 
      all NHL analytics in this project.
    database: dbt_analytics
    schema: staging
    loader: python_api_extract  # the technology used to load the data
    loaded_at_field: _etl_loaded_at  # used to calculate data freshness
    
    tables:
      - name: current_standings
        description: >
          Most recent NHL team standings containing points, wins, losses, and other key metrics.
          Updated daily during the regular season and playoffs. Contains one record per team 
          for the current season.
        columns:
          - name: team_id
            description: Unique identifier for each NHL team
          - name: season
            description: NHL season identifier in YYYYZZZZ format (e.g., 20232024)
        
      - name: current_teams
        description: >
          Comprehensive information about all teams actively competing in the NHL. 
          Includes team names, abbreviations, locations, and logo URLs. This table
          contains both English and French versions of team names where applicable.
        columns:
          - name: id
            description: Unique identifier for the team
        
      - name: games
        description: >
          Basic game information for all NHL games from the 2023-2024 season start until now.
          Includes game identifiers, dates, times, and participating teams. This table
          serves as the central reference for all game-related analytics.
        columns:
          - name: id
            description: Unique identifier for the game
          - name: season
            description: NHL season identifier
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: game_boxscore
        description: >
          Detailed boxscore statistics for each game, including comprehensive player 
          performance metrics. Contains detailed JSON objects with player stats broken
          down by game, team, and period. This is a rich data source for player performance
          analysis on a per-game basis.
        columns:
          - name: id
            description: Unique identifier for the game, matches the id in the games table
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: team_rosters
        description: >
          Current team roster information with detailed player data organized by position.
          Contains JSON arrays for forwards, defensemen, and goalies with comprehensive 
          player attributes including height, weight, birthplace, and headshot URLs.
          This data powers player profile analytics and team composition analysis.
        columns:
          - name: team_id
            description: Unique identifier for the team, matches the id in current_teams
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        
      - name: daily_standings
        description: >
          Historical daily snapshots of team standings throughout the season.
          Each record represents a team's standing metrics (points, wins, losses, etc.)
          for a specific calendar date. This historical data enables trend analysis
          and visualization of standings changes over time.
        columns:
          - name: date
            description: Calendar date of the standings snapshot
          - name: team_id
            description: Unique identifier for each team
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: game_summaries
        description: >
          Detailed statistical summaries for each game, including team-level metrics
          and individual scoring and penalty events. Contains aggregate statistics and
          JSON objects with period-by-period breakdowns. This table powers team performance
          analytics and game outcome analysis.
        columns:
          - name: id
            description: Unique identifier for the game, matches the id in the games table
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: play_by_play 
        description: >
          Chronological record of all significant plays for each NHL game.
          Contains a JSON array with detailed play events including type, time, players involved,
          and coordinates on the ice. This granular data enables detailed game analysis,
          player contribution metrics, and advanced hockey analytics like possession metrics.
        columns:
          - name: id
            description: Unique identifier for the game, matches the id in the games table
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        
      - name: season_schedules
        description: >
          Complete season schedule data for all NHL games (both played and upcoming).
          Includes game dates, times, participating teams, and game status. This table
          powers schedule analytics, team workload analysis, and upcoming game predictions.
          The data covers the entire NHL season including regular season and playoffs.
        columns:
          - name: id
            description: Unique identifier for the game
          - name: season
            description: NHL season identifier
          - name: date
            description: Scheduled date of the game
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}